version: "3"

services:
    nginx:
        build: ./nginx/
        ports:
            - 8080:80
        volumes:
            - "${PROJECT_PUBLIC_ROOT}:/var/www/html:ro"
            - "${PROJECT_ROOT}:/var/www:ro"
        networks:
            - server
        depends_on:
            - php

    php:
        build: ./php/
        expose:
            - 9000
        volumes:
            - "${PROJECT_PUBLIC_ROOT}:/var/www/html"
            - "${PROJECT_ROOT}:/var/www"
        networks:
            - database
            - server
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
        volumes:
            - data:/var/lib/mysql
        networks:
            - database
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8090:80
        networks:
            - database
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql

volumes:
    data:

networks:
    database:
    server:

