<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading"><h1>Slim</h1></div>
            <div class="panel-body">

                <h2>a microframework for PHP</h2>
                <p>Try <a href="http://www.slimframework.com">SlimFramework</a>
                </p>
            </div>
        </div>
    </div>
</div>
