<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">Login</div>
            <div class="panel-body">
                <form action="<?= $router->pathFor('login') ?>" method="post" autocomplete="off">

                    <div class="form-group<?= empty($validation_errors['email']) ? '' : ' has-error'; ?>">
                        <label for="email">Email</label>
                        <input type="email" name="email" id="email" placeholder="example@home.com" class="form-control"
                               value="<?= $previous_params['email']; ?>">
						<? if (!empty($validation_errors['email'])): ?>
                            <span class="help-block"><?= $validation_errors['email'][0]; ?></span>
						<? endif; ?>
                    </div>

                    <div class="form-group<?= empty($validation_errors['password']) ? '' : ' has-error'; ?>">
                        <label for="password">Password</label>
                        <input type="password" name="password" id="password" class="form-control">
						<? if (!empty($validation_errors['password'])): ?>
                            <span class="help-block"><?= $validation_errors['password'][0]; ?></span>
						<? endif; ?>
                    </div>

                    <button type="submit" class="btn btn-default">Login</button>
                </form>
            </div>
        </div>
    </div>
</div>
