<div>
    <form>
        <div class="form-group">
            <label for="email">email</label>
            <input type="email" class="form-control" placeholder="Email" id="email">
        </div>
        <div class="form-group">
            <label for="password">password</label>
            <input type="password" class="form-control" placeholder="Password" id="password">
        </div>
        <button type="submit" class="btn btn-default">Login</button>

    </form>
</div>
